apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
namespace: default

images:
  - name: 324702811080.dkr.ecr.us-east-1.amazonaws.com/frontend
    newName: 324702811080.dkr.ecr.us-east-1.amazonaws.com/frontend
    newTag: "82d3ed9dc95231600f9bb69184c69752489759a4"